### ISSUE TITLE
// $ExpectError tests can never fail

### ISSUE THREAD

**Issue by aaronjensen** [flowtype/flow-typed#1385]
```js
// $ExpectError
const x: number = 3;
```

That should fail, but doesn't.

**Comment by villesau** [comment]
This commit from flow changed the behaviour: https://github.com/facebook/flow/commit/c62d5ebac2ef7881192b760b023ce54bb57140e6
And there is an issue open about it: https://github.com/facebook/flow/issues/5009
Seems rather serious!

**Comment by aaronjensen** [comment]
Agreed, quite serious. I'd hate to be the one to try and reenable it on this repo. I'd guess the only way to reenable it now would be to grep for warning in the output of flow since it won't exit w/ a non-zero status code :/

**Comment by GAntoine** [comment]
Flow recently made unused suppression comments warnings instead of errors. Warnings are not included by default. (You need `include_warnings=true` in the `.flowconfig`). I'll look into how this affects running specs on travis.

**Comment by villesau** [comment]
Made a naive fix for the problem: https://github.com/flowtype/flow-typed/pull/1407 at least it should point to right direction.

**Comment by villesau** [comment]
@GAntoine it might make sense to run the test suite for all the PRs open at the moment now when the fix is merged.

**Comment by GAntoine** [comment]
Yeah that makes sense, though they'll need to rebase first. I'll go through the active ones and let people know.

**Comment by julienw** [comment]
@gantoine this is still not working: a lot of tests are not failing even though $ExpectError fails to catch an error... See the tests for react-redux_v5 as an example: they should clearly fail but currently they don't.

**Comment by julienw** [comment]
Ok, actually this works, but because in travis tests are only run on differences, we haven't seen these errors.

**Comment by villesau** [comment]
yeah would not be fair to fail tests on non-related libdefs.
