### ISSUE TITLE
Error cloning repo: spawn EACCES

### ISSUE THREAD

**Issue by Couto** [flowtype/flow-typed#481]
I confess that I don't have a nice description for this problem but this seems to happen in at least two different OSX computers.

I've tried:
 - `git clone git@github.com:flowtype/flow-typed.git` with success
 - Using npm instead of yarn **without** success

I'm providing the full log.
I'll try to provide any information you may ask.

```shell
~/Development/awesome-project master*
❯ yarn global add flow-typed
yarn global v0.17.8
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed flow-typed@2.0.0 with binaries:
      - flow-typed
warning No license field
✨  Done in 3.70s.

~/Development/awesome-project master*
❯ flow-typed install
• Found flow-bin@v0.35.0 installed. Installing libdefs compatible with this version of Flow...
• Found 37 dependencies in package.json. Searching for libdefs...
• flow-typed cache not found, fetching from GitHub...ERROR: Unable to clone the local cache repo.
UNCAUGHT ERROR: Error: Error cloning repo: spawn EACCES
    at cloneInto$ (/Users/couto/.config/yarn/global/node_modules/flow-typed/dist/lib/git.js:77:17)
    at tryCatch (/Users/couto/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/couto/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:337:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/couto/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:96:21)
    at tryCatch (/Users/couto/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:63:40)
    at invoke (/Users/couto/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:139:20)
    at /Users/couto/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:149:13
```

**Comment by Couto** [comment]
In order to provide more info:
I also can't update flow-typed's cache.

```
~
❯ flow-typed update-cache
Updating flow-typed definitions...
Update failed: Error cloning repo: spawn EACCES
```

**Comment by Couto** [comment]
So I've decided to uninstall the git version that I was using through homebrew, and flow-typed started to work again without problems.

I'm assuming there's something incompatible between flow-typed's git implementation and the current (stable 2.10.2) version of git.

**Comment by ryyppy** [comment]
in `flow-typed`, we fork child processes communicating with `git`... so I guess there might be a problem with some configuration / interface there... is this fixed now?

**Comment by shanez** [comment]
Still happening on v2.0.0

I've tried homebrew's git [ v2.11.0 ] and OSX's default [ 2.9.3 (Apple Git-75) ] and I receive the same error as above on both.

**Comment by Naddiseo** [comment]
I ran into what appears to be the same error, although I can't be sure. I got the same symptoms, but I'm running on linux. I did a bit of investigating, and it appears that flow-typed is running into https://github.com/npm/node-which/issues/37, because I have Rust installed on my computer, and have cargo's bin directory (~/.cargo/bin) in my `$PATH`. Cargo seems to have a `git` **directory**, and so when `flow-typed` tries to find the path to the git binary, it is instead returning the path to the git directory under `~/.cargo/bin`
