### ISSUE TITLE
rebasing flow-typed cache hangs

### ISSUE THREAD

**Issue by johnryan** [flowtype/flow-typed#909]
Recently running `flow-typed install --overwrite` has started hanging for 10 - 15 minutes on `rebasing flow-typed cache...`

It eventually completes but i'm not sure what might have changed that would cause the slowdown. Is there recommended way to debug this?

**Comment by doberkofler** [comment]
Having the same problem after upgrading to node 8.0.0

**Comment by johnryan** [comment]
I think it actually has to do with npm 5.x, seems to still happen if i use 5.x with lower node version

**Comment by doberkofler** [comment]
I use npm 5 with node 6 and have no problem. It breaks with node 8 for me.

**Comment by leyyinad** [comment]
Same here, hangs with node `v8.0.0`, works with node `v6.10.3`, both tried with npm `5.0.1`.

**Comment by mistadikay** [comment]
Still reproducible on node `8.1.0` and npm `5.0.3`

**Comment by doberkofler** [comment]
I did some very basic debugging and it seems to me, as if there is some memory leak that causes flow-typed to fail on node 8.1.0. Would be great, if one of the core contributors could have a look at this as it prevents to move to node 8.

**Comment by marudor** [comment]
I had this Problem as well. But not anymore. (No Idea what fixed this)

Sadly I'm not really able to look into this.
Maybe @jeffmo?

**Comment by uppe-r** [comment]
No hangs on Node `v7.8.0` with npm `v.5.x.x` or `v.4.6.1`. Guess it's really a Node `v8` problem then.

**Comment by vjpr** [comment]
`flow-typed update-cache` works fine...

```
flow-typed update-cache --debug
Updating flow-typed definitions...
• rebasing flow-typed cache...done.
Definitions update successful!
```

But same issue with 8.1.1 and install.

**Comment by vjpr** [comment]
As a workaround if you use nvm you can force flow-typed to be run with an earlier version of node.

```
nvm exec 6.5.0 flow-typed install
```

**Comment by doberkofler** [comment]
@bsonntag Did I understand you correctly, that 2.1.1 would be working with node 8 and 2.1.2 fails. That might really help to track down the problem that prevents all of us to move to node 8.

**Comment by bsonntag** [comment]
@doberkofler I'm actually using 2.0.0, but yeah, it "works" in node 8 (i.e., it doesn't hang), although I get that "malformed directory name" error described in #913.

**Comment by doberkofler** [comment]
I've now tried with the latest node 8.1.3 and npm 5.0.4 and it seems to work. Can someone else confirm?

**Comment by amilajack** [comment]
I can confirm that this works but it takes an unusual amount of time.

**Comment by bsonntag** [comment]
What do you mean by "works"? It still hangs for me with node 8.1.3.

**Comment by andykais** [comment]
`8.1.2` I was averaging over 200s for flow-typed to complete, but with node `8.1.3` I am averaging 60s, not great but still an improvement 

upgrading npm `4.6.1` to `5.0.4` seemed to have no effect

**Comment by amilajack** [comment]
@bsonntag by "works" I mean it actually completes but it still takes a long time. Previously, it never completed. @andykais downgrading node should work

**Comment by doberkofler** [comment]
Before node 8.1.3 it did not complete at all and now it takes long (an average of 300s) but it completes.

**Comment by bsonntag** [comment]
I've done some debugging and I believe the problem is in [extractLibDefsFromNpmPkgDir](https://github.com/flowtype/flow-typed/blob/326c6e8509aeb5b61472134efc13287fd43006ce/cli/src/lib/npm/npmLibDefs.js#L74).
This function seems to be running slower in node 8.

**Comment by marudor** [comment]
I've just released 2.1.3. Node8 should no longer hang

**Comment by bsonntag** [comment]
@marudor nope, still hangs.

It's taking me 8 seconds to run `flow-typed install`, and it's throwing an error anyway.

<img width="1119" alt="screen shot 2017-07-17 at 15 35 32" src="https://user-images.githubusercontent.com/6205451/28273410-3c00481c-6b06-11e7-8319-215408106f44.png">

flow-typed@2.1.3
node@8.1.4

**Comment by Rauttis** [comment]
Continues to be really slow for me also.
flow-typed@2.1.3
node@8.1.4

`flow-typed update  334.72s user 3.92s system 100% cpu 5:35.36 total`

**Comment by marudor** [comment]
Okay. Will check later.
Really not acceptable :/

**Comment by doberkofler** [comment]
I do not get an error but unfortunately it remains very slow for me as well.
flow-typed@2.1.3
node@8.1.4

**Comment by aguynamedben** [comment]
FWIW this affects https://github.com/chentsulin/electron-react-boilerplate badly when using Node 8

**Comment by pcvandamcb** [comment]
I'm sorry to be "that guy", but any update on this?

**Comment by marudor** [comment]
Sadly I can't find the problem :(
If anyone has a hint please drop it.
If I have the time I might rewrite some of it and hopefully fixing it with that...

**Comment by mistadikay** [comment]
the problem is gone for me on node@8.3.0

**Comment by pcvandamcb** [comment]
Can confirm. 8.3.0 fixes it for me.

The timing!

**Comment by marudor** [comment]
Thats awesome news!

**Comment by vnctaing** [comment]
8.3.0 fixes it, but it is still slow. (took me 730s, when usually it took few dozens of seconds)

**Comment by doberkofler** [comment]
Unfortunately the same here.

**Comment by bradennapier** [comment]
v8.4.0 appears to fix this issue.  Wow.  Glad I finally got fed up and searched :-P not sure when I would have updated otherwise.

**Comment by po5i** [comment]
Confirmed. Node 8.4 fixes this issue.

**Comment by kjg531** [comment]
For people of the future, this also works on node 10.0
